export enum CourseEnum{
    POO = 'PROGRAMACION ORIENTADA A OBJETOS',
    QUIMICA_ORGANICA = 'QUIMICA ORGANICA',
    FISICA_CUANTICA = 'FISICA CUANTICA',
    PROGRAMACION_WEB = 'PROGRAMACION WEB',
    ELECTRONICA = 'ELECTRONICA',
}